# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pessoasdb
    username: pessoasuser
    password: senhaforte
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
